Add number proccess locked by an other one
criteo-forks/collectd-python-mysql pull request #7
Opened 2020-02-14 18:14 UTC by Esysteme

2020-02-15 12:37 UTC, CharlesJUDITH commented
Can you add at least a description to describe the change? Thx

2020-02-15 12:45 UTC, CharlesJUDITH commented
You should also mention that this new metric is available only when using the metadata_lock plugin: https://mariadb.com/kb/en/information-schema-metadata_lock_info-table/

2020-02-15 16:30 UTC, CharlesJUDITH requested changes

2020-02-15 16:30 UTC, CharlesJUDITH commented on mysql.py
> +	dispatch_value('mariadb', 'lock', meta_data_lock['nb_lock'], 'gauge')
why not using something like information_schema as this is coming from the information_schema table.

2020-02-19 10:11 UTC, Esysteme commented
updated index to innodb

2020-02-20 09:20 UTC, khodin approved these changes

2020-02-20 09:22 UTC, merged